# Generated by Django 3.0.8 on 2020-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_auto_20201016_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('genap', 'Genap'), ('ganjil', 'Ganjil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tahunpelajaran',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
