# Generated by Django 3.0.8 on 2020-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sekarang', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='active', max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='pria', max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('tanggal_masuk', models.DateField()),
                ('nomor_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
