# Generated by Django 3.0.8 on 2020-10-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
        ('utama', '0002_auto_20201016_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dari_semester_sebelumnya', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('lunas', 'Lunas')], default='aktif', max_length=20)),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Siswa')),
                ('smester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Semester')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.TahunPelajaran')),
                ('untuk_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.Kelas')),
            ],
            options={
                'ordering': ['murid', 'smester'],
            },
        ),
        migrations.CreateModel(
            name='TandaTerima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dibayar', models.IntegerField()),
                ('tanggal_bayar', models.DateField()),
                ('keterangan', models.CharField(blank=True, max_length=125, null=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.Tagihan')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=100)),
                ('jumlah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.BiayaPendaftaran')),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.Tagihan')),
            ],
        ),
    ]
